[package]
name = "another-chess"
version = "0.1.0"
authors = ["username <flandare@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.0"
strum = "0.20"
strum_macros = "0.20"
